// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protobuf

package org.apache.drill.jig.proto;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public final class ExecuteRequest implements Externalizable, Message<ExecuteRequest>, Schema<ExecuteRequest>
{

    public static Schema<ExecuteRequest> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static ExecuteRequest getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ExecuteRequest DEFAULT_INSTANCE = new ExecuteRequest();

    
    private String statement;

    public ExecuteRequest()
    {
        
    }

    public ExecuteRequest(
        String statement
    )
    {
        this.statement = statement;
    }

    // getters and setters

    // statement

    public String getStatement()
    {
        return statement;
    }

    public ExecuteRequest setStatement(String statement)
    {
        this.statement = statement;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<ExecuteRequest> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public ExecuteRequest newMessage()
    {
        return new ExecuteRequest();
    }

    public Class<ExecuteRequest> typeClass()
    {
        return ExecuteRequest.class;
    }

    public String messageName()
    {
        return ExecuteRequest.class.getSimpleName();
    }

    public String messageFullName()
    {
        return ExecuteRequest.class.getName();
    }

    public boolean isInitialized(ExecuteRequest message)
    {
        return 
            message.statement != null;
    }

    public void mergeFrom(Input input, ExecuteRequest message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.statement = input.readString();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, ExecuteRequest message) throws IOException
    {
        if(message.statement == null)
            throw new UninitializedMessageException(message);
        output.writeString(1, message.statement, false);
    }

    public String getFieldName(int number)
    {
        switch(number)
        {
            case 1: return "statement";
            default: return null;
        }
    }

    public int getFieldNumber(String name)
    {
        final Integer number = __fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    private static final java.util.HashMap<String,Integer> __fieldMap = new java.util.HashMap<String,Integer>();
    static
    {
        __fieldMap.put("statement", 1);
    }
    
}
