// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protobuf

package org.apache.drill.jig.proto;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class ListLoginsResponse implements Externalizable, Message<ListLoginsResponse>, Schema<ListLoginsResponse>
{

    public static Schema<ListLoginsResponse> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static ListLoginsResponse getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ListLoginsResponse DEFAULT_INSTANCE = new ListLoginsResponse();

    
    private List<String> loginTypes;

    public ListLoginsResponse()
    {
        
    }

    // getters and setters

    // loginTypes

    public List<String> getLoginTypesList()
    {
        return loginTypes;
    }

    public ListLoginsResponse setLoginTypesList(List<String> loginTypes)
    {
        this.loginTypes = loginTypes;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<ListLoginsResponse> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public ListLoginsResponse newMessage()
    {
        return new ListLoginsResponse();
    }

    public Class<ListLoginsResponse> typeClass()
    {
        return ListLoginsResponse.class;
    }

    public String messageName()
    {
        return ListLoginsResponse.class.getSimpleName();
    }

    public String messageFullName()
    {
        return ListLoginsResponse.class.getName();
    }

    public boolean isInitialized(ListLoginsResponse message)
    {
        return true;
    }

    public void mergeFrom(Input input, ListLoginsResponse message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    if(message.loginTypes == null)
                        message.loginTypes = new ArrayList<String>();
                    message.loginTypes.add(input.readString());
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, ListLoginsResponse message) throws IOException
    {
        if(message.loginTypes != null)
        {
            for(String loginTypes : message.loginTypes)
            {
                if(loginTypes != null)
                    output.writeString(1, loginTypes, true);
            }
        }
    }

    public String getFieldName(int number)
    {
        switch(number)
        {
            case 1: return "loginTypes";
            default: return null;
        }
    }

    public int getFieldNumber(String name)
    {
        final Integer number = __fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    private static final java.util.HashMap<String,Integer> __fieldMap = new java.util.HashMap<String,Integer>();
    static
    {
        __fieldMap.put("loginTypes", 1);
    }
    
}
