// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protobuf

package org.apache.drill.jig.proto;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class LoginPropertiesResponse implements Externalizable, Message<LoginPropertiesResponse>, Schema<LoginPropertiesResponse>
{

    public static Schema<LoginPropertiesResponse> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static LoginPropertiesResponse getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final LoginPropertiesResponse DEFAULT_INSTANCE = new LoginPropertiesResponse();

    
    private String loginType;
    private String driverClass;
    private List<PropertyDef> properties;

    public LoginPropertiesResponse()
    {
        
    }

    // getters and setters

    // loginType

    public String getLoginType()
    {
        return loginType;
    }

    public LoginPropertiesResponse setLoginType(String loginType)
    {
        this.loginType = loginType;
        return this;
    }

    // driverClass

    public String getDriverClass()
    {
        return driverClass;
    }

    public LoginPropertiesResponse setDriverClass(String driverClass)
    {
        this.driverClass = driverClass;
        return this;
    }

    // properties

    public List<PropertyDef> getPropertiesList()
    {
        return properties;
    }

    public LoginPropertiesResponse setPropertiesList(List<PropertyDef> properties)
    {
        this.properties = properties;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<LoginPropertiesResponse> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public LoginPropertiesResponse newMessage()
    {
        return new LoginPropertiesResponse();
    }

    public Class<LoginPropertiesResponse> typeClass()
    {
        return LoginPropertiesResponse.class;
    }

    public String messageName()
    {
        return LoginPropertiesResponse.class.getSimpleName();
    }

    public String messageFullName()
    {
        return LoginPropertiesResponse.class.getName();
    }

    public boolean isInitialized(LoginPropertiesResponse message)
    {
        return true;
    }

    public void mergeFrom(Input input, LoginPropertiesResponse message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.loginType = input.readString();
                    break;
                case 2:
                    message.driverClass = input.readString();
                    break;
                case 3:
                    if(message.properties == null)
                        message.properties = new ArrayList<PropertyDef>();
                    message.properties.add(input.mergeObject(null, PropertyDef.getSchema()));
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, LoginPropertiesResponse message) throws IOException
    {
        if(message.loginType != null)
            output.writeString(1, message.loginType, false);

        if(message.driverClass != null)
            output.writeString(2, message.driverClass, false);

        if(message.properties != null)
        {
            for(PropertyDef properties : message.properties)
            {
                if(properties != null)
                    output.writeObject(3, properties, PropertyDef.getSchema(), true);
            }
        }

    }

    public String getFieldName(int number)
    {
        switch(number)
        {
            case 1: return "loginType";
            case 2: return "driverClass";
            case 3: return "properties";
            default: return null;
        }
    }

    public int getFieldNumber(String name)
    {
        final Integer number = __fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    private static final java.util.HashMap<String,Integer> __fieldMap = new java.util.HashMap<String,Integer>();
    static
    {
        __fieldMap.put("loginType", 1);
        __fieldMap.put("driverClass", 2);
        __fieldMap.put("properties", 3);
    }
    
}
