// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protobuf

package org.apache.drill.jig.proto;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public final class LoginRequest implements Externalizable, Message<LoginRequest>, Schema<LoginRequest>
{

    public static Schema<LoginRequest> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static LoginRequest getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final LoginRequest DEFAULT_INSTANCE = new LoginRequest();

    
    private String loginType;
    private List<PropertyValue> properties;

    public LoginRequest()
    {
        
    }

    public LoginRequest(
        String loginType
    )
    {
        this.loginType = loginType;
    }

    // getters and setters

    // loginType

    public String getLoginType()
    {
        return loginType;
    }

    public LoginRequest setLoginType(String loginType)
    {
        this.loginType = loginType;
        return this;
    }

    // properties

    public List<PropertyValue> getPropertiesList()
    {
        return properties;
    }

    public LoginRequest setPropertiesList(List<PropertyValue> properties)
    {
        this.properties = properties;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<LoginRequest> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public LoginRequest newMessage()
    {
        return new LoginRequest();
    }

    public Class<LoginRequest> typeClass()
    {
        return LoginRequest.class;
    }

    public String messageName()
    {
        return LoginRequest.class.getSimpleName();
    }

    public String messageFullName()
    {
        return LoginRequest.class.getName();
    }

    public boolean isInitialized(LoginRequest message)
    {
        return 
            message.loginType != null;
    }

    public void mergeFrom(Input input, LoginRequest message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.loginType = input.readString();
                    break;
                case 2:
                    if(message.properties == null)
                        message.properties = new ArrayList<PropertyValue>();
                    message.properties.add(input.mergeObject(null, PropertyValue.getSchema()));
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, LoginRequest message) throws IOException
    {
        if(message.loginType == null)
            throw new UninitializedMessageException(message);
        output.writeString(1, message.loginType, false);

        if(message.properties != null)
        {
            for(PropertyValue properties : message.properties)
            {
                if(properties != null)
                    output.writeObject(2, properties, PropertyValue.getSchema(), true);
            }
        }

    }

    public String getFieldName(int number)
    {
        switch(number)
        {
            case 1: return "loginType";
            case 2: return "properties";
            default: return null;
        }
    }

    public int getFieldNumber(String name)
    {
        final Integer number = __fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    private static final java.util.HashMap<String,Integer> __fieldMap = new java.util.HashMap<String,Integer>();
    static
    {
        __fieldMap.put("loginType", 1);
        __fieldMap.put("properties", 2);
    }
    
}
