// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protobuf

package org.apache.drill.jig.proto;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public final class PropertyDef implements Externalizable, Message<PropertyDef>, Schema<PropertyDef>
{

    public static Schema<PropertyDef> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static PropertyDef getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final PropertyDef DEFAULT_INSTANCE = new PropertyDef();

    
    private String name;
    private String value;
    private PropertyType type;

    public PropertyDef()
    {
        
    }

    public PropertyDef(
        String name
    )
    {
        this.name = name;
    }

    // getters and setters

    // name

    public String getName()
    {
        return name;
    }

    public PropertyDef setName(String name)
    {
        this.name = name;
        return this;
    }

    // value

    public String getValue()
    {
        return value;
    }

    public PropertyDef setValue(String value)
    {
        this.value = value;
        return this;
    }

    // type

    public PropertyType getType()
    {
        return type == null ? PropertyType.STRING : type;
    }

    public PropertyDef setType(PropertyType type)
    {
        this.type = type;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<PropertyDef> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public PropertyDef newMessage()
    {
        return new PropertyDef();
    }

    public Class<PropertyDef> typeClass()
    {
        return PropertyDef.class;
    }

    public String messageName()
    {
        return PropertyDef.class.getSimpleName();
    }

    public String messageFullName()
    {
        return PropertyDef.class.getName();
    }

    public boolean isInitialized(PropertyDef message)
    {
        return 
            message.name != null;
    }

    public void mergeFrom(Input input, PropertyDef message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.name = input.readString();
                    break;
                case 2:
                    message.value = input.readString();
                    break;
                case 3:
                    message.type = PropertyType.valueOf(input.readEnum());
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, PropertyDef message) throws IOException
    {
        if(message.name == null)
            throw new UninitializedMessageException(message);
        output.writeString(1, message.name, false);

        if(message.value != null)
            output.writeString(2, message.value, false);

        if(message.type != null)
             output.writeEnum(3, message.type.number, false);
    }

    public String getFieldName(int number)
    {
        switch(number)
        {
            case 1: return "name";
            case 2: return "value";
            case 3: return "type";
            default: return null;
        }
    }

    public int getFieldNumber(String name)
    {
        final Integer number = __fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    private static final java.util.HashMap<String,Integer> __fieldMap = new java.util.HashMap<String,Integer>();
    static
    {
        __fieldMap.put("name", 1);
        __fieldMap.put("value", 2);
        __fieldMap.put("type", 3);
    }
    
}
