// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protobuf

package org.apache.drill.jig.proto;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public final class QueryRequest implements Externalizable, Message<QueryRequest>, Schema<QueryRequest>
{

    public static Schema<QueryRequest> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static QueryRequest getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final QueryRequest DEFAULT_INSTANCE = new QueryRequest();

    
    private String statement;
    private Integer maxResponseSizeK;
    private int maxWaitSec;

    public QueryRequest()
    {
        
    }

    public QueryRequest(
        String statement,
        Integer maxResponseSizeK
    )
    {
        this.statement = statement;
        this.maxResponseSizeK = maxResponseSizeK;
    }

    // getters and setters

    // statement

    public String getStatement()
    {
        return statement;
    }

    public QueryRequest setStatement(String statement)
    {
        this.statement = statement;
        return this;
    }

    // maxResponseSizeK

    public Integer getMaxResponseSizeK()
    {
        return maxResponseSizeK;
    }

    public QueryRequest setMaxResponseSizeK(Integer maxResponseSizeK)
    {
        this.maxResponseSizeK = maxResponseSizeK;
        return this;
    }

    // maxWaitSec

    public int getMaxWaitSec()
    {
        return maxWaitSec;
    }

    public QueryRequest setMaxWaitSec(int maxWaitSec)
    {
        this.maxWaitSec = maxWaitSec;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<QueryRequest> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public QueryRequest newMessage()
    {
        return new QueryRequest();
    }

    public Class<QueryRequest> typeClass()
    {
        return QueryRequest.class;
    }

    public String messageName()
    {
        return QueryRequest.class.getSimpleName();
    }

    public String messageFullName()
    {
        return QueryRequest.class.getName();
    }

    public boolean isInitialized(QueryRequest message)
    {
        return 
            message.statement != null 
            && message.maxResponseSizeK != null;
    }

    public void mergeFrom(Input input, QueryRequest message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.statement = input.readString();
                    break;
                case 2:
                    message.maxResponseSizeK = input.readInt32();
                    break;
                case 3:
                    message.maxWaitSec = input.readInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, QueryRequest message) throws IOException
    {
        if(message.statement == null)
            throw new UninitializedMessageException(message);
        output.writeString(1, message.statement, false);

        if(message.maxResponseSizeK == null)
            throw new UninitializedMessageException(message);
        output.writeInt32(2, message.maxResponseSizeK, false);

        if(message.maxWaitSec != 0)
            output.writeInt32(3, message.maxWaitSec, false);
    }

    public String getFieldName(int number)
    {
        switch(number)
        {
            case 1: return "statement";
            case 2: return "maxResponseSizeK";
            case 3: return "maxWaitSec";
            default: return null;
        }
    }

    public int getFieldNumber(String name)
    {
        final Integer number = __fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    private static final java.util.HashMap<String,Integer> __fieldMap = new java.util.HashMap<String,Integer>();
    static
    {
        __fieldMap.put("statement", 1);
        __fieldMap.put("maxResponseSizeK", 2);
        __fieldMap.put("maxWaitSec", 3);
    }
    
}
