// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protobuf

package org.apache.drill.jig.proto;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class SchemaResponse implements Externalizable, Message<SchemaResponse>, Schema<SchemaResponse>
{

    public static Schema<SchemaResponse> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static SchemaResponse getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final SchemaResponse DEFAULT_INSTANCE = new SchemaResponse();

    
    private List<ColumnSchema> columns;

    public SchemaResponse()
    {
        
    }

    // getters and setters

    // columns

    public List<ColumnSchema> getColumnsList()
    {
        return columns;
    }

    public SchemaResponse setColumnsList(List<ColumnSchema> columns)
    {
        this.columns = columns;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<SchemaResponse> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public SchemaResponse newMessage()
    {
        return new SchemaResponse();
    }

    public Class<SchemaResponse> typeClass()
    {
        return SchemaResponse.class;
    }

    public String messageName()
    {
        return SchemaResponse.class.getSimpleName();
    }

    public String messageFullName()
    {
        return SchemaResponse.class.getName();
    }

    public boolean isInitialized(SchemaResponse message)
    {
        return true;
    }

    public void mergeFrom(Input input, SchemaResponse message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    if(message.columns == null)
                        message.columns = new ArrayList<ColumnSchema>();
                    message.columns.add(input.mergeObject(null, ColumnSchema.getSchema()));
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, SchemaResponse message) throws IOException
    {
        if(message.columns != null)
        {
            for(ColumnSchema columns : message.columns)
            {
                if(columns != null)
                    output.writeObject(1, columns, ColumnSchema.getSchema(), true);
            }
        }

    }

    public String getFieldName(int number)
    {
        switch(number)
        {
            case 1: return "columns";
            default: return null;
        }
    }

    public int getFieldNumber(String name)
    {
        final Integer number = __fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    private static final java.util.HashMap<String,Integer> __fieldMap = new java.util.HashMap<String,Integer>();
    static
    {
        __fieldMap.put("columns", 1);
    }
    
}
