// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protobuf

package org.apache.drill.jig.proto;

public enum SqlType implements com.dyuproject.protostuff.EnumLite<SqlType>
{
    VARCHAR(1);
    
    public final int number;
    
    private SqlType (int number)
    {
        this.number = number;
    }
    
    public int getNumber()
    {
        return number;
    }
    
    public static SqlType valueOf(int number)
    {
        switch(number) 
        {
            case 1: return VARCHAR;
            default: return null;
        }
    }
}
